# development:
#   adapter: sqlite3
#   database: db/data.sqlite3
#   pool: 5
#   timeout: 5000

development:
  adapter: postgresql
  encoding: unicode
  database: rack_development
  pool: 5
  username: mila
  password: gfhjkmjgznm88